#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $DIR/fxpython
cp $DIR/../python_include/flexio.py ./
docker build -t fxpython . --no-cache
popd

pushd $DIR/fxchrome
docker build -t fxchrome . --no-cache
popd



