
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="well well-lg">
                <div class="text-center">
                    <p><span class="fx-img fx-img-logo-flexio-sm"></span></p>
                    <h2><i18n>Install Flex.io</i18n></h2>
                </div>
                <div id="fx-install-step1">
                    <legend><i18n>Step 1 of 2: Connect to DBMS</i18n></legend>
                    <form>
                        <div class="form-group">
                            <p><i18n>Enter the information necessary to connect to the DBMS that will store the Flex.io directory database.</i18n></p>
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Database Type</i18n></label>
                            <select class="form-control select2" name="db_type">
                                <option value="postgres" selected>PostgreSQL</option>
                                <option value="mysql">MySQL</option>
                            </select>
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Host</i18n></label>
                            <input type="text" class="form-control" name="db_host" value="localhost" autocomplete="off" spellcheck="false">
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Port</i18n></label>
                            <input type="text" class="form-control number-input" name="db_port" value="5432" autocomplete="off" spellcheck="false">
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>DBA Username</i18n></label>
                            <input type="text" class="form-control" name="db_admin_username" value="" autocomplete="off" spellcheck="false">
                        </div>
                        <div class="form-group">
                            <label><i18n>DBA Password</i18n></label>
                            <input type="password" class="form-control" id="fx-input-db-admin-password" name="db_admin_password" value="" autocomplete="off" spellcheck="false">
                        </div>
                    </form>
                    <div class="clearfix">
                        <button type="button" class="btn btn-primary pull-right" id="fx-btn-install-step1-next"><i18n>Next</i18n> &nbsp;<span class="fa fa-arrow-circle-right"></span></button>
                    </div>
                </div>

                <div class="hidden" id="fx-install-step2">
                    <legend><i18n>Step 2 of 2: Create Flex.io Directory Database</i18n></legend>
                    <form>
                        <div class="form-group">
                            <p><i18n>Enter the name of the Flex.io directory database you wish to create as well as the user you wish to create to access the directory.</i18n></p>
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Directory Database</i18n></label>
                            <input type="text" class="form-control" name="directory_dbname" value="" autocomplete="off" spellcheck="false">
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Directory Username</i18n></label>
                            <input type="text" class="form-control" name="directory_username" value="" autocomplete="off" spellcheck="false">
                        </div>
                        <div class="form-group" data-required="true">
                            <label><i18n>Directory Password</i18n></label>
                            <input type="password" class="form-control" id="fx-input-directory-password" name="directory_password" value="" autocomplete="off" spellcheck="false">
                        </div>
                    </form>
                    <div class="clearfix">
                        <button type="button" class="btn btn-primary pull-left" id="fx-btn-install-step2-prev"><span class="fa fa-arrow-circle-left"></span>&nbsp; <i18n>Previous</i18n></button>
                        <button type="button" class="btn btn-primary pull-right" id="fx-btn-install-step2-next"><i18n>Next</i18n> &nbsp;<span class="fa fa-arrow-circle-right"></span></button>
                    </div>
                </div>

                <div class="hidden" id="fx-install-finished">
                    <legend><i18n>Installation Successful!</i18n></legend>
                    <p><i18n>Flex.io has successfully been installed.</i18n></p>
                    <form class="hidden">
                        <div class="form-group">
                            <p><i18n>A default Flex.io administrator with the following username and password has been created for you.  Keep a copy of this information in a safe place:</i18n></p>
                        </div>
                        <div class="form-group">
                            <label class="text-muted"><i18n>Username</i18n></label>
                            <p><strong class="h4" id="fx-install-admin-username">&nbsp;</strong></p>
                        </div>
                        <div class="form-group">
                            <label class="text-muted"><i18n>Password</i18n></label>
                            <p><strong class="h4" id="fx-install-admin-password">&nbsp;</strong></p>
                        </div>
                    </form>
                    <div class="clearfix">
                        <button type="button" class="btn btn-primary pull-right hidden" id="fx-btn-finish-install"><i18n>Finish</i18n> &nbsp;<span class="fa fa-arrow-circle-right"></span></button>
                        <a data-anchor="hard" href="/app/signup?invite_code=e0miwu7qkv89h3rlrnst25e3jdxbbrpn" class="btn btn-primary pull-right"><i18n>Sign Up</i18n> &nbsp;<span class="fa fa-arrow-circle-right"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->headStyle()->appendStyle("
    body {
        margin: 120px 0;
        overflow-y: auto;
    }

    footer {
        text-align: center;
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        background: #fff;
        border-top: 1px solid #eee;
        padding: 5px;
    }

    .well-lg {
        padding: 40px;
        margin-bottom: 20px;
        box-shadow: 0 1px 2px -1px rgba(0,0,0,0.4), 0 2px 2px -2px rgba(0,0,0,0.2);
        border: 0;
    }
"); ?>

<?php $this->inlineScript()->appendFile('/src/app/js/pages/install.js'); ?>
