
<div class="pos-fill fx-embed-header clearfix hidden">
    <h1></h1>
</div>
<div class="pos-fill fx-embed-body">
    <div class="pos-fill js-embed-grid" style="height: 100%"></div>
</div>
<div class="pos-fill fx-embed-footer clearfix">
    <div class="clearfix pull-left">
        <a href="https://www.flex.io" target="_blank" rel="noopener noreferrer" class="js-workspace-link pull-left tipsy" title="<i18n>Open on www.flex.io</i18n>">
            <img src="/src/img/logo-flexio-sm.png" alt="Flex.io">
        </a>
        <h1 class="pull-left"></h1>
    </div>
    <div class="pull-right">
        <button type="button" class="btn js-btn-share" data-toggle="popover" data-placement="top">
            <span class="el-icon el-icon-share"></span> <i18n>Share</i18n>
        </button>
        <button type="button" class="btn js-btn-download">
            <span class="glyphicon glyphicon-save"></span> <i18n>Download</i18n>
        </button>
        <button type="button" class="btn js-btn-fullscreen">
            <span class="glyphicon glyphicon-fullscreen"></span>
        </button>
    </div>
</div>

<script type="text/template" id="tmpl-fx-embed-share-popover">
    <div class="form-group">
        <label><i18n>Embed Code</i18n></label>
        <input type="text" class="form-control" style="width: 280px" value="<%-embed_str%>" autocomplete=off>
    </div>
    <div class="form-group">
        <label><i18n>Link</i18n></label>
        <input type="text" class="form-control" style="width: 280px" value="{{page_url}}" autocomplete=off>
    </div>
</script>

<?php $this->headStyle()->appendStyle("
    body {
        margin: 0;
    }

    header,
    footer {
        display: none !important;
    }

    .fx-embed-header,
    .fx-embed-footer {
        height: 34px;
        padding: 0 6px 0 12px;
        z-index: 10000;
    }

    .fx-embed-header {
        height: 0;
        bottom: auto;
        background: rgba(0,0,0,0.7);
        color: #fff;
    }

    .fx-embed-footer {
        top: auto;
        background: #ddd;
        color: #666;
    }

    .fx-embed-header h1,
    .fx-embed-footer h1 {
        font-size: 16px;
        line-height: 34px;
        margin: 0;
    }

    .fx-embed-footer h1 {
        margin-left: 10px;
    }

    .fx-embed-body {
        margin: 0 0 34px 0;
    }

    .fx-embed-footer .btn {
        color: #666;
        background: transparent;
        padding: 6px;
        outline: none;
    }

    .fx-embed-footer .btn:active,
    .fx-embed-footer .btn:hover {
        color: #333;
        outline: none;
    }

    .fx-embed-footer .btn + .btn {
        margin-left: 4px;
    }

    .fx-embed-footer img {
        margin-top: 7px;
        height: 18px;
    }
"); ?>

<?php
    if (IS_DEBUG())
    {
        $this->inlineScript()->appendFile('/src/js/biggrid-2.0.0/biggrid.js');
        $this->inlineScript()->appendFile('/src/js/biggrid-2.0.0/biggrid-scrollbars.js');
        $this->inlineScript()->appendFile('/src/js/biggrid-2.0.0/biggrid-plugin-defaultdropdown.js');
        $this->inlineScript()->appendFile('/src/js/biggrid-2.0.0/biggrid-plugin-columnhighlight.js');
        $this->inlineScript()->appendFile('/src/js/biggrid-2.0.0/biggrid-plugin-columndragreorder.js');
        $this->inlineScript()->appendFile('/src/app/js/pages/embedgrid.js');
    }
     else
    {
        $this->inlineScript()->appendFile('/dist/js/biggrid-2.0.0.min.js');
        $this->inlineScript()->appendFile('/dist/app/js/pages/embedgrid.min.js');
    }
?>

<?php $this->inlineScript()->captureStart() ?>
    $(function() { new FxEmbedGridPage(); })
<?php $this->inlineScript()->captureEnd() ?>
