<div class="ui segment fx-box">
    <div class="text-center" style="margin: 0 0 20px">
        <a data-anchor="hard" href="/" tabindex="1"><img src="/src/img/logo-flexio-header.png"></a>
    </div>
    <h2 class="text-center"><i18n>Forgot Password</i18n></h2>
    <div class="fx-box-inner">
        <p id="fx-message"><i18n>Enter the email address you signed up with below. An email will be sent containing a link to reset your password.</i18n></p>
        <p><i18n p1="no-reply@flex.io">You may need to check your spam folder or unblock %p1.</i18n></p>
        <form id="fx-form-forgot-password" class="fx-form-condensed">
            <div class="form-group" data-required="true">
                <input type="text" class="form-control input-lg" name="email" id="fx-input-email" placeholder="<i18n>Email</i18n>" autocomplete=off>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-lg btn-block btn-primary" id="fx-btn-forgot-password-submit" data-loading-text="<i18n>Submitting...</i18n>" autocomplete=off><i18n>Submit</i18n></button>
            </div>
        </form>
        <a data-anchor="hard" href="/app/signin" class="btn btn-lg btn-block btn-primary hidden" id="fx-btn-sign-in"><i18n>Sign in</i18n></a>
    </div>
</div>

<?php $this->headStyle()->appendStyle("
    #fx-app-header {
        display: none !important;
    }

    footer {
        display: none !important;
    }

    .ui.segment.fx-box {
        margin: 100px auto 0 auto;
        width: 748px;
        padding: 50px;
    }

    .fx-box .fx-box-inner {
        margin: 0 120px;
    }

    @media (max-width: 479px) {
        body {
            margin: 20px 0;
        }

        .ui.segment.fx-box {
            width: 80%;
            min-width: 300px;
            margin: 0 10px;
            padding: 20px;
        }

        .fx-box .fx-box-inner {
            margin: 0;
        }
    }
"); ?>

<?php
    if (IS_DEBUG())
    {
        $this->inlineScript()->appendFile('/src/app/js/pages/forgotpassword.js');
    }
     else
    {
        $this->inlineScript()->appendFile('/dist/app/js/pages/forgotpassword.min.js');
    }
?>

<?php $this->inlineScript()->captureStart() ?>
    $(function() { new FxForgotPasswordPage(); })
<?php $this->inlineScript()->captureEnd() ?>
