<div class="ui segment fx-box" id="fx-box-reset-password">
    <div class="text-center" style="margin: 0 0 20px">
        <a data-anchor="hard" href="/" tabindex="1"><img src="/src/img/logo-flexio-header.png"></a>
    </div>
    <h2 class="text-center"><i18n>Reset Password</i18n></h2>
    <div class="fx-box-inner">
        <p id="fx-message"><i18n p1="<strong><?php echo isset_or($_GET['email'], '') ?></strong>">Please enter a new password for your %p1 account.</i18n></p>
        <form id="fx-form-reset-password" class="fx-form-condensed">
            <input type="hidden" name="email" value="<?php echo isset_or($_GET['email'], '') ?>">
            <input type="hidden" name="code" value="<?php echo isset_or($_GET['code'], '') ?>">
            <div class="form-group" data-required="true">
                <input type="password" class="form-control input-lg" name="password" id="fx-input-password" placeholder="<i18n>New Password</i18n>" autocomplete=off>
            </div>
            <div class="form-group">
                <input type="password" class="form-control input-lg" name="password2" id="fx-input-confirm-password" placeholder="<i18n>Retype Password</i18n>" autocomplete=off>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-lg btn-block btn-primary" id="fx-btn-reset-password-submit" data-loading-text="<i18n>Submitting...</i18n>" autocomplete=off><i18n>Reset Password</i18n></button>
            </div>
        </form>
        <a data-anchor="hard" href="/app/signin" class="btn btn-lg btn-block btn-primary hidden" id="fx-btn-sign-in"><i18n>Sign in</i18n></a>
    </div>
</div>

<script type="text/template" id="tmpl-fx-reset-password-success">
    <h3><i18n>Your password has been reset</i18n></h3>
    <p><i18n>Your password has been successfully reset. To continue using Flex.io, you will need to sign in again.</i18n></p>
    <a data-anchor="hard" href="/app/signin" class="btn btn-block btn-primary">Sign In</a>
</script>

<?php $this->headStyle()->appendStyle("
    #fx-app-header {
        display: none !important;
    }

    footer {
        display: none !important;
    }

    .ui.segment.fx-box {
        margin: 100px auto 0 auto;
        width: 748px;
        padding: 50px;
    }

    .fx-box .fx-box-inner {
        margin: 0 120px;
    }

    @media (max-width: 479px) {
        body {
            margin: 20px 0;
        }

        .ui.segment.fx-box {
            width: 80%;
            min-width: 300px;
            margin: 0 10px;
            padding: 20px;
        }

        .fx-box .fx-box-inner {
            margin: 0;
        }
    }
"); ?>

<?php
    if (IS_DEBUG())
    {
        $this->inlineScript()->appendFile('/src/app/js/pages/resetpassword.js');
    }
     else
    {
        $this->inlineScript()->appendFile('/dist/app/js/pages/resetpassword.min.js');
    }
?>

<?php $this->inlineScript()->captureStart() ?>
    $(function() { new FxResetPasswordPage(); })
<?php $this->inlineScript()->captureEnd() ?>
