<div class="ui segment fx-box" id="fx-box-create-account">
    <div class="text-center" style="margin: 0 0 20px">
        <a data-anchor="hard" href="/" tabindex="1"><img src="/src/img/logo-flexio-header.png"></a>
    </div>
    <div class="fx-box-inner">
        <form id="fx-form-create-account">
            <h2 class="text-center"><i18n>Sign up for Flex.io</i18n></h2>
            <div class="form-group" data-required="true">
                <label class="sr-only"><i18n>First name</i18n></label>
                <input type="text" class="form-control input-lg" id="fx-input-first-name" name="first_name" placeholder="<i18n>First name</i18n>" autocomplete=off>
            </div>
            <div class="form-group" data-required="true">
                <label class="sr-only"><i18n>Last name</i18n></label>
                <input type="text" class="form-control input-lg" id="fx-input-last-name" name="last_name" placeholder="<i18n>Last name</i18n>" autocomplete=off>
            </div>
            <div class="form-group" data-required="true">
                <label class="sr-only"><i18n>Pick a username</i18n></label>
                <input type="text" class="form-control input-lg" id="fx-input-user-name" name="user_name" placeholder="<i18n>Pick a username</i18n>" data-fieldname="Username" autocomplete=off>
                <div class="help-block small text-danger"></div>
            </div>
            <div class="form-group" data-required="true">
                <label class="sr-only"><i18n>Email</i18n></label>
                <input type="text" class="form-control input-lg" id="fx-input-email" name="email" placeholder="<i18n>Email</i18n>" autocomplete=off>
                <div class="help-block small text-danger"></div>
            </div>
            <div class="form-group" data-min-length="8">
                <label class="sr-only"><i18n>Password</i18n></label>
                <input type="password" class="form-control input-lg" id="fx-input-password" name="password" placeholder="<i18n>Password</i18n>" autocomplete=off>
                <div class="help-block small text-danger"></div>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-lg btn-block btn-primary" id="fx-btn-create-account" data-loading-text="<i18n>Creating account...</i18n>" autocomplete=off>
                    <i18n>Sign up</i18n>
                </button>
                <div class="help-block small text-muted" id="fx-terms-notice">
                    <i18n>By signing up, you agree to Flex.io's Terms of Service and Privacy Policy.</i18n>
                </div>
            </div>
        </form>
    </div>
    <hr>
    <div class="text-center text-md">
        <i18n>Already have an account?</i18n>&nbsp;<a data-anchor="hard" href="/app/signin?<?php echo $_SERVER['QUERY_STRING']; ?>"><i18n>Sign in</i18n></a>
    </div>
</div>

<script type="text/template" id="tmpl-fx-signup-success">
    <h3><i18n>Thanks for signing up!</i18n></h3>
    <p>{{msg}}</p>
    <p><i18n>If you don't see the email in your inbox, please check your junk mail or spam folder.</i18n></p>
    <button type="button" class="btn btn-block btn-primary" id="fx-btn-resend-email" data-loading-text="<i18n>Sending...</i18n>"><i18n>Resend Email</i18n></button>
</script>

<?php $this->headStyle()->appendStyle("
    #fx-app-header {
        display: none !important;
    }

    footer {
        display: none !important;
    }

    .ui.segment.fx-box {
        margin: 100px auto 0 auto;
        width: 748px;
        padding: 50px;
    }

    .fx-box .fx-box-inner {
        margin: 0 120px;
    }

    @media (max-width: 479px) {
        body {
            margin: 20px 0;
        }

        .ui.segment.fx-box {
            width: 80%;
            min-width: 300px;
            margin: 0 10px;
            padding: 20px;
        }

        .fx-box .fx-box-inner {
            margin: 0;
        }
    }
"); ?>

<?php
    if (IS_DEBUG())
    {
        $this->inlineScript()->appendFile('/src/app/js/pages/signup.js');
    }
     else
    {
        $this->inlineScript()->appendFile('/dist/app/js/pages/signup.min.js');
    }
?>

<?php $this->inlineScript()->captureStart() ?>
    $(function() { new FxSignUpPage(); })
<?php $this->inlineScript()->captureEnd() ?>
