<div class="ui segment fx-box" id="fx-box-create-account">
    <div class="text-center" style="margin: 0 0 20px">
        <a data-anchor="hard" href="/" tabindex="1"><img src="/src/img/logo-flexio-header.png"></a>
    </div>
    <div class="fx-box-inner">
        <form id="fx-form-sign-in">
            <h2 class="text-center"><i18n>Sign in</i18n></h2>
            <div class="form-group">
                <label class="sr-only"><i18n>Email or username</i18n></label>
                <input type="text" class="form-control input-lg" id="fx-input-email" name="username" placeholder="<i18n>Email or username</i18n>" tabindex="2" autocomplete=off>
            </div>
            <div class="form-group">
                <label class="sr-only"><i18n>Password</i18n></label>
                <input type="password" class="form-control input-lg" id="fx-input-password" name="password" placeholder="<i18n>Password</i18n>" tabindex="3" autocomplete=off>
                <div class="help-block small text-muted">
                    <a data-anchor="hard" href="/app/forgotpassword" class="text-muted" tabindex="4"><i18n>Forgot your password?</i18n></a>
                </div>
            </div>
            <div class="form-group hidden" style="margin-top: -10px">
                <div class="clearfix">
                    <div class="checkbox text-muted pull-right">
                        <label><input type="checkbox" name="remember_me" tabindex="5" autocomplete=off> <i18n>Keep me signed in</i18n></label>
                   </div>
                </div>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-lg btn-block btn-primary" id="fx-btn-sign-in" data-loading-text="<i18n>Signing in...</i18n>" tabindex="6" autocomplete=off>
                    <i18n>Sign in</i18n>
                </button>
            </div>
        </form>
    </div>
    <hr>
    <div class="text-center text-md">
        <i18n>New to Flex.io?</i18n>&nbsp;<a data-anchor="hard" href="/app/signup?<?php echo $_SERVER['QUERY_STRING']; ?>" tabindex="7"><i18n>Sign up</i18n></a>
    </div>
</div>

<?php $this->headStyle()->appendStyle("
    #fx-app-header {
        display: none !important;
    }

    footer {
        display: none !important;
    }

    .ui.segment.fx-box {
        margin: 100px auto 0 auto;
        width: 748px;
        padding: 50px;
    }

    .fx-box .fx-box-inner {
        margin: 0 120px;
    }

    @media (max-width: 479px) {
        body {
            margin: 20px 0;
        }

        .ui.segment.fx-box {
            width: 80%;
            min-width: 300px;
            margin: 0 10px;
            padding: 20px;
        }

        .fx-box .fx-box-inner {
            margin: 0;
        }
    }
"); ?>

<?php
    if (IS_DEBUG())
    {
        $this->inlineScript()->appendFile('/src/app/js/pages/signin.js');
    }
     else
    {
        $this->inlineScript()->appendFile('/dist/app/js/pages/signin.min.js');
    }
?>

<?php $this->inlineScript()->captureStart() ?>
    $(function() { new FxSignInPage(); })
<?php $this->inlineScript()->captureEnd() ?>
