
<div class="fx-page">
    <div class="container" style="margin-top: 20px">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2>Lorem ipsum dolor sit amet.</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae dictum mi. Quisque commodo laoreet rutrum. Aenean tincidunt sagittis egestas. Praesent blandit interdum lectus, id facilisis eros consectetur ac. In pulvinar malesuada erat, nec posuere risus aliquet non. Vestibulum pellentesque fermentum pharetra. Ut in turpis sit amet massa laoreet varius. Cras pulvinar, felis eu dictum aliquet, felis dolor lobortis diam, vitae rhoncus dolor nulla vel orci. Integer libero odio, rhoncus vel purus et, scelerisque vulputate orci. Nulla pharetra sapien vehicula, luctus mi nec, facilisis lorem. Sed et nibh arcu. Fusce sed egestas velit. Duis sodales ornare molestie. Nam tortor arcu, euismod in neque nec, fermentum posuere risus. Nunc in maximus ipsum. Sed vehicula quis augue sit amet fringilla.</p>
                <p>Here's a quick sample pipe you can test out:</p>
                <iframe src="https://localhost/app/embed?eid=gbwxdwjd8nw7" width="100%" height="70" frameborder="0" allowfullscreen></iframe>
                <p>Fusce rutrum egestas massa quis aliquet. Suspendisse posuere bibendum sem, at varius mauris molestie at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum sapien purus, vestibulum ut lacus et, ultricies egestas risus. Aenean bibendum non nisl ut tincidunt. Ut sit amet elit nec purus ultricies tristique vel ac odio. Duis at massa et nunc sagittis aliquam eget et ligula. Mauris porta sodales risus, nec pulvinar metus placerat eu. Pellentesque auctor tristique quam sit amet dapibus. In venenatis, quam id laoreet cursus, lacus felis ullamcorper urna, eget pharetra nisi nulla sit amet tortor. Nam varius euismod ex vulputate ornare. Fusce commodo sodales nulla. Donec ultrices pulvinar felis sed mattis. Nam eleifend nunc magna, quis ultricies sapien gravida pulvinar. Pellentesque eget ante nibh. In id sollicitudin elit, at pellentesque sapien.</p>
                <p>Pellentesque ornare tortor ipsum, quis maximus mauris commodo in. Aliquam pretium turpis ut varius laoreet. Proin accumsan, mi ac laoreet lobortis, metus eros dapibus ligula, nec imperdiet dolor eros venenatis justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin rutrum massa et mollis pulvinar. Ut lobortis massa suscipit vehicula elementum. Pellentesque sollicitudin, tortor ut accumsan interdum, odio libero ullamcorper odio, non lacinia orci est vitae dolor. Aenean egestas turpis elit, in tristique risus lobortis non. Aliquam lectus tellus, cursus sit amet nisi non, accumsan rutrum metus. Aenean placerat tincidunt facilisis. Vestibulum semper lectus eget porttitor sollicitudin. Duis ut ultricies quam, a sollicitudin nunc.</p>
                <!--<iframe src="https://localhost/embed?eid=czgw1mq4q1k5&res_eid=dfg0ms4sz06r" width="600" height="450" title="payments" frameborder="0" allowfullscreen></iframe>-->
                <p>Ut posuere semper quam. Nam mattis viverra condimentum. Nunc id aliquam nibh. Nam tempus, ante nec hendrerit rhoncus, dui neque mollis mauris, et egestas massa sem a nulla. Quisque ultrices mi lacinia semper pellentesque. Sed nec sapien at ipsum egestas porttitor. Vivamus sed sapien nulla. Vivamus ut lobortis purus.</p>
            </div>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart() ?>
$(function() {
    $('.fx-page').appendTo('#fx-app-content');
});
<?php $this->inlineScript()->captureEnd() ?>
