<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <?php echo $this->headTitle(); ?>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://s3.amazonaws.com/flexio-app-assets/apple-touch-icon.png">
    <link rel="icon" href="https://s3.amazonaws.com/flexio-app-assets/favicon.png">

    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
  </head>
  <body>
    <div id="app">
      <?php echo $this->content; ?>
      <?php echo $this->inlineScript(); // append scripts from the view fragment ?>
    </div>
</html>
