diff -u ..\mysql\Action.php Action.php
diff -u ..\mysql\Action.php Action.php
diff -u ..\mysql\Connection.php Connection.php
diff -u ..\mysql\Pipe.php Pipe.php
diff -u ..\mysql\Process.php Process.php
diff -u ..\mysql\Project.php Project.php
diff -u ..\mysql\Registry.php Registry.php
diff -u ..\mysql\SearchModel.php SearchModel.php
diff -u ..\mysql\StreamModel.php StreamModel.php
diff -u ..\mysql\TempdataModel.php TempdataModel.php
diff -u ..\mysql\TokenModel.php TokenModel.php
diff -u ..\mysql\UserModel.php UserModel.php
