diff -u ..\mysql\Action.php Action.php
diff -u ..\mysql\Action.php Action.php
diff -u ..\mysql\Connection.php Connection.php
diff -u ..\mysql\Pipe.php Pipe.php
diff -u ..\mysql\Process.php Process.php
diff -u ..\mysql\Registry.php Registry.php
diff -u ..\mysql\Search.php Search.php
diff -u ..\mysql\Stream.php Stream.php
diff -u ..\mysql\Tempdata.php Tempdata.php
diff -u ..\mysql\Token.php Token.php
diff -u ..\mysql\User.php User.php
