# Flex.io application
FROM ubuntu:16.04
MAINTAINER Ben Williams <ben@flex.io>
ARG VERSION=master

RUN apt-get -y update
#RUN apt-get -y upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" upgrade -y
RUN apt-get -y install apt-utils
RUN apt-get -y install openssh-client
RUN apt-get -y install git

RUN cat /dev/zero | ssh-keygen -q -N ""

RUN apt-get -y install apache2
RUN service apache2 stop
RUN apt-get -y install php7.2
RUN apt-get -y install libapache2-mod-php7.2
RUN apt-get -y install php7.2-curl php7.2-dev php7.2-gd php7.2-opcache php7.2-pgsql php7.2-mysql php7.2-sqlite3 php7.2-xml php7.2-mbstring php7.2-intl php7.2-zip
RUN apt-get -y install php-redis
RUN apt-get -y install php-zmq
RUN apt-get -y install composer



COPY id_rsa /root/.ssh/id_rsa_github
COPY id_rsa.pub /root/.ssh/id_rsa_github.pub
RUN echo Host github.com >> /root/.ssh/config
RUN echo HostName github.com >> /root/.ssh/config
RUN echo User git >> /root/.ssh/config
RUN echo IdentityFile /root/.ssh/id_rsa_github >> /root/.ssh/config
RUN echo StrictHostKeyChecking no >> /root/.ssh/config >> /root/.ssh/config
RUN chmod 600 /root/.ssh/id_rsa_github
RUN chmod 644 /root/.ssh/id_rsa_github.pub

RUN mkdir -p /srv/www/flexio/log
#RUN mkdir -p /srv/www/flexio/ssl
RUN git clone git@github.com:flexiodata/flexio.git /srv/www/flexio/src

# note that if VERSION is not set, it will simply fail and the source
# will simply stay on the master branch
RUN cd /srv/www/flexio/src && git checkout tags/${VERSION}

RUN cd /srv/www/flexio/src && export HOME=/root && composer install

#RUN rm /root/.ssh/id_rsa_github
#RUN rm /root/.ssh/id_rsa_github.pub

COPY config.json /srv/www/flexio/src/config/config.json

#RUN cd /srv/www/flexio/src && git checkout develop
#RUN cp /srv/www/flexio/src/scripts/webserver/apache-ssl.conf /etc/apache2/sites-available
RUN cp /srv/www/flexio/src/scripts/webserver/apache.conf /etc/apache2/sites-available/flexio.conf
#RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /srv/www/flexio/ssl/app_flex_io.key -out /srv/www/flexio/ssl/app_flex_io.crt -subj "/C=US/ST=Illinois/L=Chicago/O=Flex.io/OU=Development/CN=app.flex.io"
RUN a2dissite 000-default
RUN a2ensite flexio
RUN a2enmod headers rewrite
#RUN a2enmode ssl


# creation of docker images
RUN apt-get -y install docker.io
RUN /srv/www/flexio/src/scripts/docker/build-docker-images

# allow www-data to run docker containers
RUN usermod -a -G docker www-data

#RUN apt-get -y install python3-pip
#RUN pip3 install Pillow


# add fstab entry for efs
RUN apt-get -y install nfs-common
RUN mkdir -p /srv/www/flexio/store
RUN echo fs-2f426b66.efs.us-east-1.amazonaws.com:/ /srv/www/flexio/store nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0 >> /etc/fstab


RUN service apache2 start

# mark status as done
RUN curl -X POST https://fjaxox0kwc.execute-api.us-east-1.amazonaws.com/default/flexio-update-buildinfo?environment=test&contents=DONE


