#!/bin/bash

PACKAGE=flexiocli
VERSION=1.0
PKGVERSION=1
ARCH=amd64

DIR=${PACKAGE}_${VERSION}-${PKGVERSION}
rm -rf $DIR
mkdir $DIR
mkdir $DIR/DEBIAN
mkdir $DIR/usr
mkdir $DIR/usr/bin


echo Package: flexiocli                  > $DIR/DEBIAN/control
echo Version: ${VERSION}-${PKGVERSION}  >> $DIR/DEBIAN/control
echo Section: base                      >> $DIR/DEBIAN/control
echo Priority: optional                 >> $DIR/DEBIAN/control
echo Architecture: ${ARCH}              >> $DIR/DEBIAN/control
echo Depends:                           >> $DIR/DEBIAN/control
echo Maintainer: admin@flex.io          >> $DIR/DEBIAN/control
echo "Description: The flex.io Command Line Interface " >> $DIR/DEBIAN/control
echo " is a tool used to manage your Flex.io resources" >> $DIR/DEBIAN/control
echo " and services.                                  " >> $DIR/DEBIAN/control

cp ../flexio $DIR/usr/bin
dpkg-deb --build $DIR ${PACKAGE}-${VERSION}-${ARCH}.deb


