<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Flex.io</title>
    <style>
      body {
        display: none;
      }
    </style>
  <body>
    <script>
      /*
      var search = window.location.search.substring(1)
      var json = JSON.parse('{"' + decodeURI(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}')
      */

      try
      {
        var info = JSON.stringify(<?php echo $this->flexio_oauth_info; ?>)
        localStorage.setItem('flexio:oauth-callback-info', info)
      }
      catch(e)
      {
      }

      // close the oauth window
      window.close()
    </script>
  </body>
</html>
