
<?php $this->headStyle()->appendStyle("
    body {
        display: none;
    }
"); ?>

<?php $this->inlineScript()->captureStart() ?>
  document.body.onload = onLoad

  function onLoad() {
    var search = window.location.search.substring(1)
    var json = JSON.parse('{"' + decodeURI(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}')

    // close the oauth window
    window.getOauthParams = function() { return json }
    window.close()
  }
<?php $this->inlineScript()->captureEnd() ?>
