<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Flex.io</title>
    <style>
      body {
        display: none;
      }
    </style>
  <body>
    <script>
      /*
      var search = window.location.search.substring(1)
      var json = JSON.parse('{"' + decodeURI(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}')
      */

      try
      {
        var oauth_json = <?php echo $this->service_oauth_response; ?>;
        window.opener.postMessage(oauth_json, "*")
      }
      catch(e)
      {
      }

      // TODO: should we still close this window here?
      // close the oauth window
      //window.close()
    </script>
  </body>
</html>
