<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Flex.io</title>
    <style>
      html,
      body {
        margin: 0;
        padding: 0;
        height: 100%;
        overflow: hidden;
        position: relative;
      }

      #content {
        position: fixed;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
      }
    </style>
  <body>
    <script>
      window.location = '<?php echo $this->service_oauth_url; ?>'
    </script>
  </body>
</html>
