<h1 class="content-title">Utilities</h1>
<div class="well">
    <ol class="util-list">
        <li><a data-anchor="hard" href="/util/generatesprite">Generate Image Sprite</a></li>
        <li><a data-anchor="hard" href="/util/generatebase64png">Generate Base64 PNGs</a></li>
        <li><a data-anchor="hard" href="/util/findtrailingcommas">Find Trailing Commas in Code</a></li>
    </ol>
</div>

<?php $this->headStyle()->appendStyle("
    #page-content {
        margin: 48px;
    }

    .content-title {
        margin-bottom: 24px;
        font-size: 26px;
        padding-bottom: 8px;
        border-bottom: 1px solid #999999;
    }

    .util-list {
        margin-bottom: 0;
    }

    .util-list li {
        font-size: 16px;
        line-height: 32px;
    }
"); ?>
